### ISSUE TITLE
BUG : problem of library import

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/types-js#6] opened 2024-05-28 08:56 UTC
**Describe the bug**
When using this lib in ts-node, I have a compilation message error :
```
TSError: ⨯ Unable to compile TypeScript:
src/tmp/26.testSepolia.ts:12:28 - error TS1479: 
The current file is a CommonJS module whose imports will produce 'require' calls; 
however, the referenced file is an ECMAScript module and cannot be imported with 'require'. 
Consider writing a dynamic 'import("starknet-types")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', 
or add the field `"type": "module"` to '/home/edmond/Documents/starknet/starknet.js-workshop-typescript/package.json'.

12 import { WALLET_API } from "starknet-types";
                              ~~~~~~~~~~~~~~~~
```

**To Reproduce**
- create a TS script, including :
```typescript
import { WALLET_API } from "starknet-types";
```
- using this package.json :
```json
{
  "name": "starknet-js-typescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest",
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "starknet": "6.9.0",
    "starknet-merkle-tree": "^1.0.2",
    "starknet-types": "^0.7.2",
  },
  "devDependencies": {
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
  }
}
```
- and this tsconfig.json :
```json
{
  "compilerOptions": {
    "target":"ES2022",
    "lib": [
      "es2022",
      "dom"
    ],
    "outDir": "./out",
    "rootDir": "./src",
    "incremental": true,
    "module": "Node16",
    "moduleResolution": "Node16",
    "resolveJsonModule": true,
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "isolatedModules": true,
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
-  try to compile
```bash
ts-node ./script.ts
```

**Expected behavior**
Use of this library with my project config, without compilation error.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker] : any
- Node version [e.g. 16.0.1] : ts-node@10.9.2
- library version : 0.7.2

**Additional context**
I am using this project config for a long time, without any problem on many libraries, except this one.

**Comment by tabaktoni** [comment] 2024-06-05 16:03
The issue is that your bundle project is CommonJS so you can switch to new es-module or you can use type import:
`import type { SomeWalletApiType } from '@starknet-io/types-js'`
maybe you will need to use "moduleResolution": "Bundler" if you stay on Commonjs.
This is not strictly a ts-types issue but I can do an example on your project if you still have this issue? so that others can copy the solution.

**Comment by PhilippeR26** [comment] 2024-06-05 16:11
A script that handles the problem : https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/Starknet131/Starknet131-sepolia/2.testZeroable.ts

**Comment by tabaktoni** [comment] 2024-06-18 15:50
Link is deprecated, can we close this one ?

**Comment by PhilippeR26** [comment] 2024-06-18 16:27
Unfortunately the problem is still there :
https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/Starknet131/Starknet131-devnet/10.testZeroable.ts

**Comment by tabaktoni** [comment] 2024-11-19 11:23
Yea because ts-node is fixating on type and not resolving exports.
https://github.com/TypeStrong/ts-node/issues/935#issuecomment-1872164284
https://stackoverflow.com/questions/63742790/unable-to-import-esm-ts-module-in-node/74608156#74608156
This setup works without any issue with tsx.

Anyway, I can propose this solution at the moment check if it's working for you:
https://github.com/starknet-io/types-js/pull/23

**Comment by PhilippeR26** [comment] 2024-11-26 15:59
You know what? 
It works!!!
![image](https://github.com/user-attachments/assets/76ba077a-d305-472b-8467-b13edecad6b6)

So happy :)

**Closed** 2024-11-27 14:56 UTC
